/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AverageRating { 'track' : Track, 'averageRating' : number }
export type ExternalBlob = Uint8Array;
export interface Rating { 'raterUserId' : Principal, 'score' : bigint }
export interface Track {
  'id' : string,
  'audioFileKey' : ExternalBlob,
  'title' : string,
  'ownerId' : Principal,
  'ratings' : Array<Rating>,
  'description' : string,
  'uploadTimestamp' : bigint,
  'artist' : string,
  'coverKey' : [] | [ExternalBlob],
}
export interface UserProfile {
  'profilePicKey' : [] | [ExternalBlob],
  'username' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, [] | [ExternalBlob]],
    undefined
  >,
  'deleteTrack' : ActorMethod<[string], undefined>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnTracks' : ActorMethod<[], Array<Track>>,
  'getTrackAverageRating' : ActorMethod<[string], number>,
  'getTrackById' : ActorMethod<[string], [] | [Track]>,
  'getTracksSortedByRating' : ActorMethod<[], Array<AverageRating>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateTrack' : ActorMethod<[string, bigint], undefined>,
  'uploadTrack' : ActorMethod<
    [string, string, string, string, ExternalBlob, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];