/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AverageRating { 'track' : Track, 'averageRating' : number }
export interface Battle {
  'id' : string,
  'status' : BattleStatus,
  'expiresAt' : [] | [bigint],
  'winnerId' : [] | [Principal],
  'votes' : Array<BattleVote>,
  'defenderTrackId' : [] | [string],
  'challengerTrackId' : string,
  'createdAt' : bigint,
  'defenderId' : Principal,
  'challengerId' : Principal,
  'acceptedAt' : [] | [bigint],
}
export type BattleSide = { 'challenger' : null } |
  { 'defender' : null };
export type BattleStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'declined' : null };
export interface BattleVote { 'side' : BattleSide, 'voterId' : Principal }
export interface Comment {
  'id' : string,
  'authorId' : Principal,
  'text' : string,
  'trackId' : string,
  'timestamp' : bigint,
}
export interface CommentReply {
  'id' : string,
  'commentId' : string,
  'authorId' : Principal,
  'text' : string,
  'timestamp' : bigint,
}
export interface EmailSubscriber { 'subscribedAt' : bigint, 'email' : string }
export type ExternalBlob = Uint8Array;
export interface MusicRequest {
  'id' : string,
  'fromUserId' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'toArtistId' : Principal,
}
export interface Notification {
  'id' : string,
  'requestId' : [] | [string],
  'notifType' : { 'newTrack' : null } |
    { 'requestReply' : null },
  'trackTitle' : string,
  'trackId' : string,
  'timestamp' : bigint,
  'replyText' : [] | [string],
  'fromArtistId' : Principal,
}
export interface Playlist {
  'id' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'trackIds' : Array<string>,
  'isPublic' : boolean,
}
export interface Rating { 'raterUserId' : Principal, 'score' : bigint }
export interface RequestReply {
  'requestId' : string,
  'artistId' : Principal,
  'timestamp' : bigint,
  'replyText' : string,
}
export interface Track {
  'id' : string,
  'region' : string,
  'audioFileKey' : ExternalBlob,
  'title' : string,
  'ownerId' : Principal,
  'city' : string,
  'ratings' : Array<Rating>,
  'description' : string,
  'uploadTimestamp' : bigint,
  'likes' : Array<Principal>,
  'state' : string,
  'genre' : string,
  'artist' : string,
  'coverKey' : [] | [ExternalBlob],
}
export interface UserProfile {
  'profilePicKey' : [] | [ExternalBlob],
  'username' : string,
  'bgStyle' : string,
  'bannerKey' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBattle' : ActorMethod<[Principal, string], string>,
  'createOrUpdateProfile' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [ExternalBlob], string],
    undefined
  >,
  'createPlaylist' : ActorMethod<[string, Array<string>, boolean], string>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'deleteTrack' : ActorMethod<[string], undefined>,
  'finalizeBattle' : ActorMethod<[string], undefined>,
  'followArtist' : ActorMethod<[Principal], undefined>,
  'getActiveBattles' : ActorMethod<[], Array<Battle>>,
  'getBattleById' : ActorMethod<[string], [] | [Battle]>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForTrack' : ActorMethod<[string], Array<Comment>>,
  'getEmailSubscriberCount' : ActorMethod<[], bigint>,
  'getEmailSubscribers' : ActorMethod<[], Array<EmailSubscriber>>,
  'getFollowedArtists' : ActorMethod<[], Array<Principal>>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getMusicRequestsSentByMe' : ActorMethod<[], Array<MusicRequest>>,
  'getMyBattles' : ActorMethod<[], Array<Battle>>,
  'getMyMusicRequests' : ActorMethod<[], Array<MusicRequest>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getMyRequestReplies' : ActorMethod<
    [],
    Array<[MusicRequest, [] | [RequestReply]]>
  >,
  'getOwnTracks' : ActorMethod<[], Array<Track>>,
  'getPendingBattlesForMe' : ActorMethod<[], Array<Battle>>,
  'getPlaylistById' : ActorMethod<[string], [] | [Playlist]>,
  'getPublicPlaylistsByOwner' : ActorMethod<[Principal], Array<Playlist>>,
  'getRepliesForComment' : ActorMethod<[string], Array<CommentReply>>,
  'getReplyForRequest' : ActorMethod<[string], [] | [RequestReply]>,
  'getTopThreeTracks' : ActorMethod<[], Array<AverageRating>>,
  'getTrackAverageRating' : ActorMethod<[string], number>,
  'getTrackById' : ActorMethod<[string], [] | [Track]>,
  'getTracksByOwner' : ActorMethod<[Principal], Array<Track>>,
  'getTracksFilteredByLocation' : ActorMethod<
    [string, string, string],
    Array<AverageRating>
  >,
  'getTracksSortedByRating' : ActorMethod<[], Array<AverageRating>>,
  'getTracksSortedByRatingInWindow' : ActorMethod<
    [string],
    Array<AverageRating>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likeTrack' : ActorMethod<[string], undefined>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'rateTrack' : ActorMethod<[string, bigint], undefined>,
  'replyToComment' : ActorMethod<[string, string], undefined>,
  'replyToMusicRequest' : ActorMethod<[string, string], undefined>,
  'respondToBattle' : ActorMethod<[string, string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMusicRequest' : ActorMethod<[Principal, string], undefined>,
  'subscribeToEmailList' : ActorMethod<[string], undefined>,
  'unfollowArtist' : ActorMethod<[Principal], undefined>,
  'unlikeTrack' : ActorMethod<[string], undefined>,
  'updatePlaylist' : ActorMethod<
    [string, string, Array<string>, boolean],
    undefined
  >,
  'uploadTrack' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      [] | [ExternalBlob],
      string,
      string,
      string,
    ],
    undefined
  >,
  'voteInBattle' : ActorMethod<[string, BattleSide], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];