/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'profilePicKey' : IDL.Opt(ExternalBlob),
  'username' : IDL.Text,
});
export const Rating = IDL.Record({
  'raterUserId' : IDL.Principal,
  'score' : IDL.Nat,
});
export const Track = IDL.Record({
  'id' : IDL.Text,
  'audioFileKey' : ExternalBlob,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'ratings' : IDL.Vec(Rating),
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'artist' : IDL.Text,
  'coverKey' : IDL.Opt(ExternalBlob),
});
export const AverageRating = IDL.Record({
  'track' : Track,
  'averageRating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'deleteTrack' : IDL.Func([IDL.Text], [], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'getTrackAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getTrackById' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
  'getTracksSortedByRating' : IDL.Func([], [IDL.Vec(AverageRating)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateTrack' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadTrack' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'profilePicKey' : IDL.Opt(ExternalBlob),
    'username' : IDL.Text,
  });
  const Rating = IDL.Record({
    'raterUserId' : IDL.Principal,
    'score' : IDL.Nat,
  });
  const Track = IDL.Record({
    'id' : IDL.Text,
    'audioFileKey' : ExternalBlob,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'ratings' : IDL.Vec(Rating),
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'artist' : IDL.Text,
    'coverKey' : IDL.Opt(ExternalBlob),
  });
  const AverageRating = IDL.Record({
    'track' : Track,
    'averageRating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'deleteTrack' : IDL.Func([IDL.Text], [], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'getTrackAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getTrackById' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
    'getTracksSortedByRating' : IDL.Func(
        [],
        [IDL.Vec(AverageRating)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateTrack' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadTrack' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };