/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'profilePicKey' : IDL.Opt(ExternalBlob),
  'username' : IDL.Text,
  'bgStyle' : IDL.Text,
  'bannerKey' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Principal,
  'text' : IDL.Text,
  'trackId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MusicRequest = IDL.Record({
  'id' : IDL.Text,
  'fromUserId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'toArtistId' : IDL.Principal,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'trackTitle' : IDL.Text,
  'trackId' : IDL.Text,
  'timestamp' : IDL.Int,
  'fromArtistId' : IDL.Principal,
});
export const Rating = IDL.Record({
  'raterUserId' : IDL.Principal,
  'score' : IDL.Nat,
});
export const Track = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'audioFileKey' : ExternalBlob,
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'city' : IDL.Text,
  'ratings' : IDL.Vec(Rating),
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'likes' : IDL.Vec(IDL.Principal),
  'state' : IDL.Text,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'coverKey' : IDL.Opt(ExternalBlob),
});
export const AverageRating = IDL.Record({
  'track' : Track,
  'averageRating' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deleteTrack' : IDL.Func([IDL.Text], [], []),
  'followArtist' : IDL.Func([IDL.Principal], [], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForTrack' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getFollowedArtists' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getMusicRequestsSentByMe' : IDL.Func([], [IDL.Vec(MusicRequest)], ['query']),
  'getMyMusicRequests' : IDL.Func([], [IDL.Vec(MusicRequest)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOwnTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'getTrackAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getTrackById' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
  'getTracksByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Track)], ['query']),
  'getTracksFilteredByLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(AverageRating)],
      ['query'],
    ),
  'getTracksSortedByRating' : IDL.Func([], [IDL.Vec(AverageRating)], ['query']),
  'getTracksSortedByRatingInWindow' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AverageRating)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likeTrack' : IDL.Func([IDL.Text], [], []),
  'markNotificationsRead' : IDL.Func([], [], []),
  'rateTrack' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMusicRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unfollowArtist' : IDL.Func([IDL.Principal], [], []),
  'unlikeTrack' : IDL.Func([IDL.Text], [], []),
  'uploadTrack' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'profilePicKey' : IDL.Opt(ExternalBlob),
    'username' : IDL.Text,
    'bgStyle' : IDL.Text,
    'bannerKey' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Principal,
    'text' : IDL.Text,
    'trackId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MusicRequest = IDL.Record({
    'id' : IDL.Text,
    'fromUserId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'toArtistId' : IDL.Principal,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'trackTitle' : IDL.Text,
    'trackId' : IDL.Text,
    'timestamp' : IDL.Int,
    'fromArtistId' : IDL.Principal,
  });
  const Rating = IDL.Record({
    'raterUserId' : IDL.Principal,
    'score' : IDL.Nat,
  });
  const Track = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'audioFileKey' : ExternalBlob,
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'city' : IDL.Text,
    'ratings' : IDL.Vec(Rating),
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'likes' : IDL.Vec(IDL.Principal),
    'state' : IDL.Text,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'coverKey' : IDL.Opt(ExternalBlob),
  });
  const AverageRating = IDL.Record({
    'track' : Track,
    'averageRating' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob), IDL.Text],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deleteTrack' : IDL.Func([IDL.Text], [], []),
    'followArtist' : IDL.Func([IDL.Principal], [], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForTrack' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getFollowedArtists' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getMusicRequestsSentByMe' : IDL.Func(
        [],
        [IDL.Vec(MusicRequest)],
        ['query'],
      ),
    'getMyMusicRequests' : IDL.Func([], [IDL.Vec(MusicRequest)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOwnTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'getTrackAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getTrackById' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
    'getTracksByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Track)], ['query']),
    'getTracksFilteredByLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(AverageRating)],
        ['query'],
      ),
    'getTracksSortedByRating' : IDL.Func(
        [],
        [IDL.Vec(AverageRating)],
        ['query'],
      ),
    'getTracksSortedByRatingInWindow' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AverageRating)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likeTrack' : IDL.Func([IDL.Text], [], []),
    'markNotificationsRead' : IDL.Func([], [], []),
    'rateTrack' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMusicRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unfollowArtist' : IDL.Func([IDL.Principal], [], []),
    'unlikeTrack' : IDL.Func([IDL.Text], [], []),
    'uploadTrack' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };