/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BattleVote {
    side: BattleSide;
    voterId: Principal;
}
export interface Track {
    id: string;
    region: string;
    audioFileKey: ExternalBlob;
    title: string;
    ownerId: Principal;
    city: string;
    ratings: Array<Rating>;
    description: string;
    uploadTimestamp: bigint;
    likes: Array<Principal>;
    state: string;
    genre: string;
    artist: string;
    coverKey?: ExternalBlob;
}
export interface Rating {
    raterUserId: Principal;
    score: bigint;
}
export interface Comment {
    id: string;
    authorId: Principal;
    text: string;
    trackId: string;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MusicRequest {
    id: string;
    fromUserId: Principal;
    message: string;
    timestamp: bigint;
    toArtistId: Principal;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AverageRating {
    track: Track;
    averageRating: number;
}
export interface RequestReply {
    requestId: string;
    artistId: Principal;
    timestamp: bigint;
    replyText: string;
}
export interface CommentReply {
    id: string;
    commentId: string;
    authorId: Principal;
    text: string;
    timestamp: bigint;
}
export interface Notification {
    id: string;
    requestId?: string;
    notifType: Variant_newTrack_requestReply;
    trackTitle: string;
    trackId: string;
    timestamp: bigint;
    replyText?: string;
    fromArtistId: Principal;
}
export interface EmailSubscriber {
    subscribedAt: bigint;
    email: string;
}
export interface Battle {
    id: string;
    status: BattleStatus;
    expiresAt?: bigint;
    winnerId?: Principal;
    votes: Array<BattleVote>;
    defenderTrackId?: string;
    challengerTrackId: string;
    createdAt: bigint;
    defenderId: Principal;
    challengerId: Principal;
    acceptedAt?: bigint;
}
export interface UserProfile {
    profilePicKey?: ExternalBlob;
    username: string;
    bgStyle: string;
    bannerKey?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BattleSide {
    challenger = "challenger",
    defender = "defender"
}
export enum BattleStatus {
    active = "active",
    pending = "pending",
    completed = "completed",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_newTrack_requestReply {
    newTrack = "newTrack",
    requestReply = "requestReply"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(trackId: string, text: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBattle(defenderArtistId: Principal, challengerTrackId: string): Promise<string>;
    createOrUpdateProfile(username: string, profilePicKey: ExternalBlob | null, bannerKey: ExternalBlob | null, bgStyle: string): Promise<void>;
    deleteComment(commentId: string): Promise<void>;
    deleteTrack(id: string): Promise<void>;
    finalizeBattle(battleId: string): Promise<void>;
    followArtist(artistId: Principal): Promise<void>;
    getActiveBattles(): Promise<Array<Battle>>;
    getBattleById(battleId: string): Promise<Battle | null>;
    getCallerProfile(): Promise<UserProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsForTrack(trackId: string): Promise<Array<Comment>>;
    getEmailSubscriberCount(): Promise<bigint>;
    getEmailSubscribers(): Promise<Array<EmailSubscriber>>;
    getFollowedArtists(): Promise<Array<Principal>>;
    getFollowerCount(artistId: Principal): Promise<bigint>;
    getMusicRequestsSentByMe(): Promise<Array<MusicRequest>>;
    getMyBattles(): Promise<Array<Battle>>;
    getMyMusicRequests(): Promise<Array<MusicRequest>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyRequestReplies(): Promise<Array<[MusicRequest, RequestReply | null]>>;
    getOwnTracks(): Promise<Array<Track>>;
    getPendingBattlesForMe(): Promise<Array<Battle>>;
    getRepliesForComment(commentId: string): Promise<Array<CommentReply>>;
    getReplyForRequest(requestId: string): Promise<RequestReply | null>;
    getTopThreeTracks(): Promise<Array<AverageRating>>;
    getTrackAverageRating(id: string): Promise<number>;
    getTrackById(id: string): Promise<Track | null>;
    getTracksByOwner(owner: Principal): Promise<Array<Track>>;
    getTracksFilteredByLocation(windowType: string, locationType: string, locationValue: string): Promise<Array<AverageRating>>;
    getTracksSortedByRating(): Promise<Array<AverageRating>>;
    getTracksSortedByRatingInWindow(windowType: string): Promise<Array<AverageRating>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(artistId: Principal): Promise<boolean>;
    likeTrack(trackId: string): Promise<void>;
    markNotificationsRead(): Promise<void>;
    rateTrack(trackId: string, score: bigint): Promise<void>;
    replyToComment(commentId: string, text: string): Promise<void>;
    replyToMusicRequest(requestId: string, replyText: string): Promise<void>;
    respondToBattle(battleId: string, defenderTrackId: string, accept: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMusicRequest(toArtistId: Principal, message: string): Promise<void>;
    subscribeToEmailList(email: string): Promise<void>;
    unfollowArtist(artistId: Principal): Promise<void>;
    unlikeTrack(trackId: string): Promise<void>;
    uploadTrack(id: string, title: string, artist: string, description: string, genre: string, audioFileKey: ExternalBlob, coverKey: ExternalBlob | null, city: string, state: string, region: string): Promise<void>;
    voteInBattle(battleId: string, side: BattleSide): Promise<void>;
}
import type { AverageRating as _AverageRating, Battle as _Battle, BattleSide as _BattleSide, BattleStatus as _BattleStatus, BattleVote as _BattleVote, ExternalBlob as _ExternalBlob, MusicRequest as _MusicRequest, Notification as _Notification, Rating as _Rating, RequestReply as _RequestReply, Track as _Track, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBattle(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBattle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBattle(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: ExternalBlob | null, arg2: ExternalBlob | null, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteTrack(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrack(arg0);
            return result;
        }
    }
    async finalizeBattle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeBattle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeBattle(arg0);
            return result;
        }
    }
    async followArtist(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followArtist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followArtist(arg0);
            return result;
        }
    }
    async getActiveBattles(): Promise<Array<Battle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBattles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBattles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBattleById(arg0: string): Promise<Battle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBattleById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBattleById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsForTrack(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForTrack(arg0);
            return result;
        }
    }
    async getEmailSubscriberCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailSubscriberCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailSubscriberCount();
            return result;
        }
    }
    async getEmailSubscribers(): Promise<Array<EmailSubscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailSubscribers();
            return result;
        }
    }
    async getFollowedArtists(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowedArtists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowedArtists();
            return result;
        }
    }
    async getFollowerCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowerCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowerCount(arg0);
            return result;
        }
    }
    async getMusicRequestsSentByMe(): Promise<Array<MusicRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMusicRequestsSentByMe();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMusicRequestsSentByMe();
            return result;
        }
    }
    async getMyBattles(): Promise<Array<Battle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBattles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBattles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMusicRequests(): Promise<Array<MusicRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMusicRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMusicRequests();
            return result;
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRequestReplies(): Promise<Array<[MusicRequest, RequestReply | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequestReplies();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequestReplies();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnTracks(): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnTracks();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnTracks();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingBattlesForMe(): Promise<Array<Battle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBattlesForMe();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBattlesForMe();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepliesForComment(arg0: string): Promise<Array<CommentReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepliesForComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepliesForComment(arg0);
            return result;
        }
    }
    async getReplyForRequest(arg0: string): Promise<RequestReply | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyForRequest(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyForRequest(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopThreeTracks(): Promise<Array<AverageRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopThreeTracks();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopThreeTracks();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrackAverageRating(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackAverageRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackAverageRating(arg0);
            return result;
        }
    }
    async getTrackById(arg0: string): Promise<Track | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackById(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackById(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTracksByOwner(arg0: Principal): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTracksByOwner(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTracksByOwner(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTracksFilteredByLocation(arg0: string, arg1: string, arg2: string): Promise<Array<AverageRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTracksFilteredByLocation(arg0, arg1, arg2);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTracksFilteredByLocation(arg0, arg1, arg2);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTracksSortedByRating(): Promise<Array<AverageRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTracksSortedByRating();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTracksSortedByRating();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTracksSortedByRatingInWindow(arg0: string): Promise<Array<AverageRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTracksSortedByRatingInWindow(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTracksSortedByRatingInWindow(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async likeTrack(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeTrack(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async rateTrack(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateTrack(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateTrack(arg0, arg1);
            return result;
        }
    }
    async replyToComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToComment(arg0, arg1);
            return result;
        }
    }
    async replyToMusicRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToMusicRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToMusicRequest(arg0, arg1);
            return result;
        }
    }
    async respondToBattle(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToBattle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToBattle(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMusicRequest(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMusicRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMusicRequest(arg0, arg1);
            return result;
        }
    }
    async subscribeToEmailList(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToEmailList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToEmailList(arg0);
            return result;
        }
    }
    async unfollowArtist(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowArtist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowArtist(arg0);
            return result;
        }
    }
    async unlikeTrack(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeTrack(arg0);
            return result;
        }
    }
    async uploadTrack(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob, arg6: ExternalBlob | null, arg7: string, arg8: string, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadTrack(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadTrack(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async voteInBattle(arg0: string, arg1: BattleSide): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteInBattle(arg0, to_candid_BattleSide_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteInBattle(arg0, to_candid_BattleSide_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AverageRating_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AverageRating): Promise<AverageRating> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_BattleSide_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BattleSide): BattleSide {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_BattleStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BattleStatus): BattleStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BattleVote_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BattleVote): BattleVote {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Battle_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Battle): Battle {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Notification_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Track_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Track): Promise<Track> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Battle]): Battle | null {
    return value.length === 0 ? null : from_candid_Battle_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RequestReply]): RequestReply | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Track]): Promise<Track | null> {
    return value.length === 0 ? null : await from_candid_Track_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BattleStatus;
    expiresAt: [] | [bigint];
    winnerId: [] | [Principal];
    votes: Array<_BattleVote>;
    defenderTrackId: [] | [string];
    challengerTrackId: string;
    createdAt: bigint;
    defenderId: Principal;
    challengerId: Principal;
    acceptedAt: [] | [bigint];
}): {
    id: string;
    status: BattleStatus;
    expiresAt?: bigint;
    winnerId?: Principal;
    votes: Array<BattleVote>;
    defenderTrackId?: string;
    challengerTrackId: string;
    createdAt: bigint;
    defenderId: Principal;
    challengerId: Principal;
    acceptedAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BattleStatus_n15(_uploadFile, _downloadFile, value.status),
        expiresAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.expiresAt)),
        winnerId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.winnerId)),
        votes: from_candid_vec_n19(_uploadFile, _downloadFile, value.votes),
        defenderTrackId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.defenderTrackId)),
        challengerTrackId: value.challengerTrackId,
        createdAt: value.createdAt,
        defenderId: value.defenderId,
        challengerId: value.challengerId,
        acceptedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.acceptedAt))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    side: _BattleSide;
    voterId: Principal;
}): {
    side: BattleSide;
    voterId: Principal;
} {
    return {
        side: from_candid_BattleSide_n22(_uploadFile, _downloadFile, value.side),
        voterId: value.voterId
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profilePicKey: [] | [_ExternalBlob];
    username: string;
    bgStyle: string;
    bannerKey: [] | [_ExternalBlob];
}): Promise<{
    profilePicKey?: ExternalBlob;
    username: string;
    bgStyle: string;
    bannerKey?: ExternalBlob;
}> {
    return {
        profilePicKey: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.profilePicKey)),
        username: value.username,
        bgStyle: value.bgStyle,
        bannerKey: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.bannerKey))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    requestId: [] | [string];
    notifType: {
        newTrack: null;
    } | {
        requestReply: null;
    };
    trackTitle: string;
    trackId: string;
    timestamp: bigint;
    replyText: [] | [string];
    fromArtistId: Principal;
}): {
    id: string;
    requestId?: string;
    notifType: Variant_newTrack_requestReply;
    trackTitle: string;
    trackId: string;
    timestamp: bigint;
    replyText?: string;
    fromArtistId: Principal;
} {
    return {
        id: value.id,
        requestId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.requestId)),
        notifType: from_candid_variant_n36(_uploadFile, _downloadFile, value.notifType),
        trackTitle: value.trackTitle,
        trackId: value.trackId,
        timestamp: value.timestamp,
        replyText: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.replyText)),
        fromArtistId: value.fromArtistId
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: string;
    audioFileKey: _ExternalBlob;
    title: string;
    ownerId: Principal;
    city: string;
    ratings: Array<_Rating>;
    description: string;
    uploadTimestamp: bigint;
    likes: Array<Principal>;
    state: string;
    genre: string;
    artist: string;
    coverKey: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    region: string;
    audioFileKey: ExternalBlob;
    title: string;
    ownerId: Principal;
    city: string;
    ratings: Array<Rating>;
    description: string;
    uploadTimestamp: bigint;
    likes: Array<Principal>;
    state: string;
    genre: string;
    artist: string;
    coverKey?: ExternalBlob;
}> {
    return {
        id: value.id,
        region: value.region,
        audioFileKey: await from_candid_ExternalBlob_n30(_uploadFile, _downloadFile, value.audioFileKey),
        title: value.title,
        ownerId: value.ownerId,
        city: value.city,
        ratings: value.ratings,
        description: value.description,
        uploadTimestamp: value.uploadTimestamp,
        likes: value.likes,
        state: value.state,
        genre: value.genre,
        artist: value.artist,
        coverKey: record_opt_to_undefined(await from_candid_opt_n29(_uploadFile, _downloadFile, value.coverKey))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    track: _Track;
    averageRating: number;
}): Promise<{
    track: Track;
    averageRating: number;
}> {
    return {
        track: await from_candid_Track_n41(_uploadFile, _downloadFile, value.track),
        averageRating: value.averageRating
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MusicRequest, [] | [_RequestReply]]): [MusicRequest, RequestReply | null] {
    return [
        value[0],
        from_candid_opt_n39(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    declined: null;
}): BattleStatus {
    return "active" in value ? BattleStatus.active : "pending" in value ? BattleStatus.pending : "completed" in value ? BattleStatus.completed : "declined" in value ? BattleStatus.declined : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    challenger: null;
} | {
    defender: null;
}): BattleSide {
    return "challenger" in value ? BattleSide.challenger : "defender" in value ? BattleSide.defender : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newTrack: null;
} | {
    requestReply: null;
}): Variant_newTrack_requestReply {
    return "newTrack" in value ? Variant_newTrack_requestReply.newTrack : "requestReply" in value ? Variant_newTrack_requestReply.requestReply : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Battle>): Array<Battle> {
    return value.map((x)=>from_candid_Battle_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BattleVote>): Array<BattleVote> {
    return value.map((x)=>from_candid_BattleVote_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MusicRequest, [] | [_RequestReply]]>): Array<[MusicRequest, RequestReply | null]> {
    return value.map((x)=>from_candid_tuple_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Track>): Promise<Array<Track>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Track_n41(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AverageRating>): Promise<Array<AverageRating>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AverageRating_n44(_uploadFile, _downloadFile, x)));
}
function to_candid_BattleSide_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BattleSide): _BattleSide {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profilePicKey?: ExternalBlob;
    username: string;
    bgStyle: string;
    bannerKey?: ExternalBlob;
}): Promise<{
    profilePicKey: [] | [_ExternalBlob];
    username: string;
    bgStyle: string;
    bannerKey: [] | [_ExternalBlob];
}> {
    return {
        profilePicKey: value.profilePicKey ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.profilePicKey)) : candid_none(),
        username: value.username,
        bgStyle: value.bgStyle,
        bannerKey: value.bannerKey ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.bannerKey)) : candid_none()
    };
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BattleSide): {
    challenger: null;
} | {
    defender: null;
} {
    return value == BattleSide.challenger ? {
        challenger: null
    } : value == BattleSide.defender ? {
        defender: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
